platform :ios, '13.0'

use_frameworks!

install! 'cocoapods', :deterministic_uuids => false

target 'STBaseProject_Example' do
  
  #  pod 'STBaseProject'
  
  pod 'STBaseProject/STBaseModule', :path => '../'
#  pod 'STBaseProject/STHUD', :path => '../'
  #  pod 'STBaseProject/STScanner', :path => '../'
  #  pod 'STBaseProject/STScreenshot', :path => '../'
  
#  pod 'SnapKit'
#  pod 'Alamofire'
#  pod 'SDWebImage'
#  pod "BeeHive"
#  pod "mobile-ffmpeg-full"

  
end
